name: Staking Dashboard CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.6
  validate-locales:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn run locale:validate
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      # - run: yarn test # No reason to check for tests now since they do not exist

  all:
    # This job ensures that all jobs above (now we have just build) are successful.
    needs: [check-license-lines, build, validate-locales]
    runs-on: ubuntu-latest
    steps:
      - run: echo Success
